# Generated by Django 4.0.5 on 2022-09-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_q5_alter_question_q1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cultural',
        ),
        migrations.RemoveField(
            model_name='question',
            name='design',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hospitality',
        ),
        migrations.RemoveField(
            model_name='question',
            name='logistics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q9',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tech',
        ),
    ]
