# Generated by Django 4.0.5 on 2022-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_question_content_remove_question_creativity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q3',
            field=models.CharField(default='ss', max_length=900),
            preserve_default=False,
        ),
    ]
